[package]
name = "orbits"
version = "0.1.0"
authors = ["Ricky Taylor <rickytaylor26@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston = "0.49.0"
piston2d-graphics = "0.36.0"
pistoncore-glutin_window = "0.63.0"
piston2d-opengl_graphics = "0.72.0"
ecs = { path = "../ecs" }
futures = "0.3.4"
async-trait = "0.1.30"
tokio = { version = "0.2.18", features = ["full"] }
rand = "0.7.3"
rayon = "1.3.0"
