[package]
name = "ecs"
version = "0.1.0"
authors = ["Ricky Taylor <rickytaylor26@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.7.2"
async-trait = "0.1.50"
futures = "0.3.14"
arc-swap = "1.2.0"
crossbeam-queue = "0.3.1"
bit-vec = "0.6.3"
rayon = "1.5.0"
slotmap = "1.0.3"
