[package]
name = "chunked"
version = "0.1.1"
description = "An Entity Component System that works by organising like entities into chunks"
categories = ["data-structures", "game-development"]
keywords = ["gamedev", "ecs"]
license = "MIT"
authors = ["Ricky Taylor <rickytaylor26@gmail.com>"]
homepage = "https://github.com/ricky26/chunked"
repository = "https://github.com/ricky26/chunked"
documentation = "https://docs.rs/chunked"
readme = "../../README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.7.2"
async-trait = "0.1.50"
futures = "0.3.14"
crossbeam-queue = "0.3.1"
bit-vec = "0.6.3"
rayon = "1.5.0"
tokio = { version = "1.5.0", features = ["rt"] }
